### ISSUE TITLE
Explicit schedule button to get future tweets

### ISSUE THREAD

**Issue by frabcus** [scraperwiki/twitter-search-tool#14]
I wonder if it should default to _not_ constantly updating.

So, once you enter search term it goes "getting initial backlog of tweets" (which it does in the background).

Then below would be one of those on/off sliders which if on sets it to update into the future as well, and you turn it on if you want it to schedule getting them in the future.

So in your case, you would never have turned it on.

In other cases, people can turn it off when they have enough.

See: https://github.com/frabcus/twitter-search-tool/issues/5

**Comment by IanHopkinson** [comment]
I got rate limited this morning:

![image](https://f.cloud.github.com/assets/3342745/967475/41b49be6-057a-11e3-8c38-1b52f860eaa0.png)

I don't want to delete my other searches but I'm happy to freeze them.

**Comment by IanHopkinson** [comment]
Stopping Twitter Search Tool manually from the commandline seems straight forward. I do `crontab -e` and put a hash at the start of the crontab line. I then update the status endpoint with

`curl --data "type=ok&message=Stopped" https://scraperwiki.com/api/status`

**Comment by frabcus** [comment]
frabcus: for now I was imagining a checkbox under the search input in the twitter tool

11:01   zarino  frabcus: I'd change it to have a big spinner saying "scraping backlog…" or something more user-friendly
11:02   zarino  frabcus: then once it's done, you can show something like "scraped 1031 tweets between 13 September and 17 September" with a checkbox to "get new tweets as they appear" and a red button to say "clear data and start again"
11:03   zarino  it's all a bit moot since that dataset settings page is a bit hidden and I bet most people wont find it again
