### ISSUE TITLE
Search for tweets in a location

### ISSUE THREAD

**Issue by zarino** [scraperwiki/twitter-search-tool#17]
When I use the `near:` search operator ([documented here](https://support.twitter.com/articles/71577-how-to-use-advanced-twitter-search) and linked to from the tool), I get an error…

> details: {"errors":[{"code":44,"message":"near parameter is invalid"}]}.

This is because, [hidden away on this page](https://dev.twitter.com/docs/using-search), Twitter warns us:

> The `near` operator cannot be used by the Search API. Instead you should use the `geocode` parameter.

The "geocode parameter" is a whole new GET parameter, separate from the search string, which means there's no way for me to enter it using the 'Search for Tweets' search box.

The URL the tool needs to call is something like:

```
http://twitter.com/search?q=scraperwiki&geocode=37.78,-122.39,25mi
```

**Comment by frabcus** [comment]
This user https://app.intercom.io/apps/63b0c6d4bb5f0867b6e93b0be9b569fb3a7ab1e3/conversations/363051460 wants geocoding based on the location of the user.

This is so she can get only Tweets that are by a person from a particular country.

**Comment by frabcus** [comment]
I think we could use this API to let people choose the region by typing a name:
https://dev.twitter.com/docs/api/1.1/get/geo/search

Then the geocode parameter on this to implement.
https://dev.twitter.com/docs/api/1.1/get/search/tweets

**Comment by frabcus** [comment]
This is covered really by the timezone for now.
