### ISSUE TITLE
Can't turn it off if you're being rate limited

### ISSUE THREAD

**Issue by frabcus** [scraperwiki/twitter-search-tool#5]
"However, I’m getting rate limited pretty quickly. My fourth twitter scraper was already too much. Are they scraping constantly? And if so, is there a way to limit scrapers to e.g. scraping once per day, without using custom python code?"

**Comment by frabcus** [comment]
Oh yes - also see/check does the user have other things attached to their Twitter account using the same API calls?

**Comment by frabcus** [comment]
Check also for hidden Twitter scrapers.

**Comment by ictocw** [comment]
Hi! 

No similar applications were attached to my Twitter account, only the usual stuff like twitpic/tweedeck. I removed most of them.

I don't think I had many hidden scrapers, max two. It was all within the first hour of trying the beta. 

I was testing scrapers for two immediate issues, #ing & Boston attacks, so lots of tweets. 

Will test again and let you know how it's going.

Thanks!

**Comment by ictocw** [comment]
Got it again now. Three Twitter scrapers (Ricin, Boston marathon, Fertilizer). Username is ictocw.

**Comment by frabcus** [comment]
Thanks, I'll take a look!

**Comment by frabcus** [comment]
The problem is that hiding datasets doesn't currently turn off their scheduling ("crontab"). I've manually turned the crontab off for the two hidden Twitter search datasets you had.

I've filed a bug on the platform about it: https://github.com/scraperwiki/custard/issues/179

There's a related issue in the Twitter search tool I'd like your help with, @ictocw : https://github.com/frabcus/twitter-search-tool/issues/5

Could you tell me, did you need your Twitter search tools to run scheduled and update themselves? How long did you need it to do that for? Did you expect them all to update, or did you expect some to just get current set of Tweets and stop?

Thanks for your help!

**Comment by IanHopkinson** [comment]
I'd like the ability to freeze the twitter search - now I've got the 40,000 tweets from the #InspiringWomen hashtag I don't want it running any more but want to keep the data.

I don't like the twitter search tool "silently" consuming an unknown amount of what I perceive to be a limited resource.

**Comment by frabcus** [comment]
That's a great idea!

I wonder if it should default to _not_ constantly updating.

So, once you enter search term it goes "getting initial backlog of
tweets" (which it does in the background). 

Then below would be one of those on/off sliders which if on sets it to
update into the future as well, and you turn it on if you want it to
schedule getting them in the future.

So in your case, you would never have turned it on.

In other cases, people can turn it off when they have enough.

Francis

On Thu, Aug 08, 2013 at 02:09:02AM -0700, IanHopkinson wrote:

> I'd like the ability to freeze the twitter search - now I've got the 40,000 tweets from the #InspiringWomen hashtag I don't want it running any more but want to keep the data.
> 
> I don't like the twitter search tool "silently" consuming an unknown amount of what I perceive to be a limited resource. 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/frabcus/twitter-search-tool/issues/5#issuecomment-22311414

## 

Do _you_ have an awesome idea you never quite manage to do? 
http://www.awesomefoundation.org/en/chapters/liverpool/

**Comment by IanHopkinson** [comment]
For the #InspiringWomen hashtag the initial download took 12 hours or so.

It could be little play, pause buttons.

**Comment by frabcus** [comment]
What I was thinking is it would _automatically_ get as much historical
stuff as it could.

Then when it has got all of that, it would stop.

Unless the button is on.

On Thu, Aug 08, 2013 at 02:27:19AM -0700, IanHopkinson wrote:

> For the #InspiringWomen hashtag the initial download took 12 hours or so.
> 
> It could be little play, pause buttons.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/frabcus/twitter-search-tool/issues/5#issuecomment-22312210

## 

Do _you_ have an awesome idea you never quite manage to do? 
http://www.awesomefoundation.org/en/chapters/liverpool/

**Comment by frabcus** [comment]
https://github.com/scraperwiki/custard/issues/179 is now closed, so deleted datasets are no longer rate limited

That fixes this bug.

However, I definitely think Tweet tool should only run forever into the future when explicitly told to. I've filed that as a new enhancement request here:
https://github.com/frabcus/twitter-search-tool/issues/14
