### ISSUE TITLE
Why isn't time zone or user's location included in the data?

### ISSUE THREAD

**Issue by StevenMaude** [scraperwiki/twitter-search-tool#53]
(lat, lng are largely worthless since most users don't enable this.)

**Comment by frabcus** [comment]
There have been a few customers who would find it useful - I asked
them all the other day again, and none had urgent need, so I didn't do
it.

I think we should add it - probably called something like
"user_timezone" so if we add all the other user fields it doesn't
become a mess.

Francis

**Comment by StevenMaude** [comment]
I'll take a look! (It's somewhat of a workaround for #17 too where the total number of tweets can be retrieved before they expire; get everything and then let users filter themselves.)

**Comment by StevenMaude** [comment]
Have this in `add-more-location-data` branch; the `tidy-up` branch needs merging in first as I made this branch off that one.
![location](https://cloud.githubusercontent.com/assets/3818079/3247954/a5c1a952-f189-11e3-8cd1-c25ca8c0e286.png)

**Comment by StevenMaude** [comment]
#56 covered this.
