### ISSUE TITLE
Why do I only get tweets for a couple of days and not a week?

### ISSUE THREAD

**Issue by StevenMaude** [scraperwiki/twitter-search-tool#55]
A user was complaining that they were only getting tweets for today (see [Intercom](https://app.intercom.io/apps/63b0c6d4bb5f0867b6e93b0be9b569fb3a7ab1e3/conversations/416932246)). I think I might have observed something similar:

![dates](https://cloud.githubusercontent.com/assets/3818079/3248152/88de44f6-f18b-11e3-8723-369ddfd8c3cd.png)

There are tweets going back to 4th and 5th June (today's the 11th) that I have in another dataset, so the behaviour's confusing.

**Comment by drj11** [comment]
got a link to the dataset?

**Comment by StevenMaude** [comment]
@drj11: bcvzj7q which has the same status message "from 10th Jun..." as above
(c.f. z75j2hi where there's tweets from e.g. 7th June).
