### ISSUE TITLE
OData connector for twitter fails on datetime

### ISSUE THREAD

**Issue by IanHopkinson** [scraperwiki/twitter-search-tool#58]
Testing on the Mac, the OData connector works for StockTicker information at this URL:

https://ds-ec2.scraperwiki.com/akzojrq/f41558589d5b473/cgi-bin/odata/FB

(In particular the data column renders correctly). An individual datetime line looks like this:
<d:Date m:type="Edm.DateTime">2012-05-18T00:00:00/d:Date

But it does not work for this Twitter data:

https://ds-ec2.scraperwiki.com/ffvf3yq/6e62849c5fb54b1/cgi-bin/odata/tweets
(The date column appears as null). In this case an individual date entry in the XML data looks like this:
<d:createdAt m:type="Edm.DateTime">2014-02-24T07:08:32+00:00/d:createdAt

We could fix this by simply truncating the timezone part of the createdAt field. We anticipate that this value is always +00:00 and should not impact users.

**Comment by StevenMaude** [comment]
Format in [tweet JSON](https://dev.twitter.com/docs/api/1.1/get/search/tweets) is `"created_at": "Mon Sep 24 03:35:21 +0000 2012"`

**Comment by StevenMaude** [comment]
We could do:
`data['created_at'] = dateutil.parser.parse(tweet['created_at']).replace(tzinfo=None)`

Thoughts on this @frabcus? (Is this likely to affect anyone's existing processing of Twitter data?)

**Comment by frabcus** [comment]
I think that replace just drops the timezone on the floor, which
scares me a bit!

It should at least assert it is UTC first...

Other than that I don't have any strong objections, apart from it
seems a bit daft when Tableau should just fix their software to parse
RFC standard date types...

Francis

**Comment by StevenMaude** [comment]
@frabcus Good point!

**Comment by drj11** [comment]
Is Tableau for Mac still in beta? @IanHopkinson

**Comment by StevenMaude** [comment]
Hmm. Do we just check for `+0000` in the string to confirm whether UTC or not? Or is there a nicer way?

**Comment by StevenMaude** [comment]
@drj11 No: [out officially 19th June](http://investors.tableausoftware.com/investor-news/investor-news-details/2014/Tableau-82-Brings-Data-to-the-Mac-and-Data-Storytelling-to-Everyone/default.aspx).

**Comment by frabcus** [comment]
I'm sure you can find a way :)

https://docs.python.org/2/library/datetime.html

I think you can do ".timezone"

**Comment by IanHopkinson** [comment]
Tableau for Mac just left beta, I believe I tested this in the full version
- license expires very shortly.

On 25 June 2014 16:44, David Jones notifications@github.com wrote:

> Is Tableau for Mac still in beta? @IanHopkinson
> https://github.com/IanHopkinson
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/scraperwiki/twitter-search-tool/issues/58#issuecomment-47119513
> .

## 

# 

Dr Ian Hopkinson
Lead Data Scientist
ScraperWiki Ltd
Liverpool
View my linkedin profile

# http://uk.linkedin.com/pub/ian-hopkinson/17/2a4/394/

**Comment by frabcus** [comment]
A user is reporting this on Tableau 8.2 on Windows too (https://app.intercom.io/apps/63b0c6d4bb5f0867b6e93b0be9b569fb3a7ab1e3/conversations/430835708) - he was fine on Tableau 8.1

I don't think we should fix it in the Twitter search tool - I think it is an OData specific issue and we should fix it there.

Closing here in lieue of https://github.com/scraperwiki/odata-cgi/issues/1

**Comment by frabcus** [comment]
Oh, and the stock tool working is also a bug! It isn't marking datetime when it should be.

https://github.com/scraperwiki/stock-tool/issues/15
