### ISSUE TITLE
Fetch all URLs separated by space not just one

### ISSUE THREAD

**Issue by DataMinerUK** [scraperwiki/twitter-search-tool#9]
Save list as string with urls separated by space in the SQL table

**Comment by frabcus** [comment]
Out of interest, what are you using the space separated URLs for?

**Comment by DataMinerUK** [comment]
I just want to fetch all of the urls. As SQL can't contain a list I thought just store them as a string with a space and I can make it into a list with .split(" "). I just want to gather all the urls associated with a hashtag

**Comment by frabcus** [comment]
Ah ok, so you're going to read it with code somewhere! Thanks :)

**Comment by frabcus** [comment]
In hand in pull request https://github.com/scraperwiki/twitter-search-tool/pull/42
